src/test/java/uk/gov/hmcts/reform/ccd/document/am/WelcomeTest.java

Test checkin only
```
[ ] Yes
[x] No
```

Updated the unit tests.

---

.travis.yml
build.gradle
config/owasp/suppressions.xml
src/test/java/uk/gov/hmcts/reform/ccd/document/am/WelcomeTest.java

Enabling the swagger documentation.
```
[ ] Yes
[x] No
```

Test branch

---

src/integrationTest/java/uk/gov/hmcts/reform/ccd/document/am/config/SwaggerPublisher.java

Dummy pull request.
```
[ ] Yes
[ ] No
```

Disabling the swagger publisher integration test for now. Need to enable it again.

---

src/integrationTest/java/uk/gov/hmcts/reform/ccd/document/am/controllers/GetWelcomeTest.java

Updated GetWelcomeTest

---

Jenkinsfile_CNP
charts/ccd-case-document-am-api/values.yaml
docker-compose.yml
infrastructure/main.tf
infrastructure/output.tf
infrastructure/variables.tf
src/main/resources/application.yaml

Adding the infrastructure variables for IDAM.

---

src/main/java/uk/gov/hmcts/reform/ccd/document/am/controllers/CaseDocumentAmController.java
src/main/java/uk/gov/hmcts/reform/ccd/document/am/controllers/endpoints/S2SAuthentication.java

https://tools.hmcts.net/jira/browse/AM-447
Case Document AM API-Download: Create security setup for new micro service Case Document AM API
```
[ ] Yes
[ x] No
```

AM-447- Separate S2S authentication endpoint in new controller.

---

src/test/java/uk/gov/hmcts/reform/ccd/document/am/controller/endpoints/CaseDocumentAmControllerTest.java

Story : https://tools.hmcts.net/jira/browse/AM-457
Task : https://tools.hmcts.net/jira/browse/AM-482
Case Document AM API-Download: Initial set of unit tests for AM-482 download binary content.
[ ] Yes
[ x] No

AM-482 : Tests for AM-457 - Fixed and added new JUnit tests

---

src/main/java/uk/gov/hmcts/reform/ccd/document/am/apihelper/Constants.java
src/main/java/uk/gov/hmcts/reform/ccd/document/am/controller/advice/exception/BadRequestException.java
src/main/java/uk/gov/hmcts/reform/ccd/document/am/controller/advice/exception/CaseNotFoundException.java
src/main/java/uk/gov/hmcts/reform/ccd/document/am/controller/advice/exception/UnauthorizedException.java
src/main/java/uk/gov/hmcts/reform/ccd/document/am/controller/endpoints/CaseDocumentAmController.java
src/main/java/uk/gov/hmcts/reform/ccd/document/am/service/CaseDataStoreService.java
src/main/java/uk/gov/hmcts/reform/ccd/document/am/service/DocumentManagementService.java
src/main/java/uk/gov/hmcts/reform/ccd/document/am/service/impl/CaseDataStoreServiceImpl.java
src/main/java/uk/gov/hmcts/reform/ccd/document/am/service/impl/DocumentManagementServiceImpl.java
src/test/java/uk/gov/hmcts/reform/ccd/document/am/controller/endpoints/CaseDocumentAmControllerTest.java

https://tools.hmcts.net/jira/browse/AM-485
Case Document AM API-Download: Implement 'Download document(binary content) from Doc-store' API at case-document micro-service.AM-485
```
[ ] Yes
[x ] No
```

AM-485- Code Refactor from controller to service layer.

---

src/main/java/uk/gov/hmcts/reform/ccd/document/am/controller/advice/exception/ResourceNotFoundException.java
src/main/java/uk/gov/hmcts/reform/ccd/document/am/service/impl/DocumentManagementServiceImpl.java

https://tools.hmcts.net/jira/browse/AM-572
Response code mismatch, expected: 404, actual: 400
```
[ ] Yes
[x ] No
```

AM-572- Fixed response status code defect.

---

build.gradle

https://tools.hmcts.net/jira/browse/AM-583
Implementation Mutation Testing
```
[ ] Yes
[x ] No
```

Implementation Mutation Testing

---

src/main/java/uk/gov/hmcts/reform/ccd/document/am/apihelper/Constants.java
src/main/java/uk/gov/hmcts/reform/ccd/document/am/controller/advice/exception/CaseNotFoundException.java
src/main/java/uk/gov/hmcts/reform/ccd/document/am/controller/advice/exception/ForbiddenException.java
src/main/java/uk/gov/hmcts/reform/ccd/document/am/controller/endpoints/CaseDocumentAmController.java
src/main/java/uk/gov/hmcts/reform/ccd/document/am/model/StoredDocumentHalResource.java
src/main/java/uk/gov/hmcts/reform/ccd/document/am/service/DocumentManagementService.java
src/main/java/uk/gov/hmcts/reform/ccd/document/am/service/impl/CaseDataStoreServiceImpl.java
src/main/java/uk/gov/hmcts/reform/ccd/document/am/service/impl/DocumentManagementServiceImpl.java
src/test/java/uk/gov/hmcts/reform/ccd/document/am/controller/endpoints/CaseDocumentAmControllerTest.java

https://tools.hmcts.net/jira/browse/AM-573
Apply Permission on get document metadata API.
```
[ ] Yes
[x ] No
```

AM-573- apply the permission on getDocument Meta data API.

---

Jenkinsfile_CNP
charts/ccd-case-document-am-api/values.preview.template.yaml
charts/ccd-case-document-am-api/values.yaml
config/owasp/suppressions.xml
infrastructure/main.tf
src/main/java/uk/gov/hmcts/reform/ccd/document/am/configuration/ApplicationConfiguration.java
src/main/java/uk/gov/hmcts/reform/ccd/document/am/controller/advice/exception/ServiceException.java
src/main/java/uk/gov/hmcts/reform/ccd/document/am/service/impl/DocumentManagementServiceImpl.java
src/main/java/uk/gov/hmcts/reform/ccd/document/am/util/JsonFeignResponseHelper.java
src/main/java/uk/gov/hmcts/reform/ccd/document/am/util/ResponseHelper.java
src/main/java/uk/gov/hmcts/reform/ccd/document/am/util/SecurityUtils.java

https://tools.hmcts.net/jira/browse/AM-582
Conversion of Feign client to rest template at service layer
```
[ ] Yes
[x ] No
```

Am 582 conversion of feign client to rest template

---

src/functionalTest/resources/features/F-002/F-002-Base-Root.td.json
src/functionalTest/resources/features/F-002/F-002.feature
src/functionalTest/resources/features/F-002/F-002_Test_Data_Base.td.json
src/functionalTest/resources/features/F-002/S-020.td.json
src/functionalTest/resources/features/F-002/S-021.td.json
src/functionalTest/resources/features/F-002/S-022.td.json
src/functionalTest/resources/features/F-002/S-023.td.json

https://tools.hmcts.net/jira/browse/AM-457
Implementing functional tests AM-457: Case Document AM API-Download - document binary content.
[ ] Yes
[x] No

AM-457: Case Document AM API-Download - document binary content functional tests

---

src/main/java/uk/gov/hmcts/reform/ccd/document/am/controller/endpoints/CaseDocumentAm.java
src/main/java/uk/gov/hmcts/reform/ccd/document/am/controller/endpoints/CaseDocumentAmController.java
src/main/java/uk/gov/hmcts/reform/ccd/document/am/model/CaseDocumentMetadata.java
src/main/java/uk/gov/hmcts/reform/ccd/document/am/model/Document.java
src/main/java/uk/gov/hmcts/reform/ccd/document/am/model/StoredDocumentHalResource.java
src/main/java/uk/gov/hmcts/reform/ccd/document/am/service/CaseDataStoreService.java
src/main/java/uk/gov/hmcts/reform/ccd/document/am/service/DocumentManagementService.java
src/main/java/uk/gov/hmcts/reform/ccd/document/am/service/impl/CaseDataStoreServiceImpl.java
src/main/java/uk/gov/hmcts/reform/ccd/document/am/service/impl/DocumentManagementServiceImpl.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/ccd/document/am/controller/endpoints/CaseDocumentAmControllerTest.java

https://tools.hmcts.net/jira/browse/AM-587
AM-587:  endpoint integration
```
[ ] Yes
[X] No
```

AM-587:  endpoint integration

---

src/functionalTest/resources/features/F-005/F-005.feature

https://tools.hmcts.net/jira/browse/AM-509
Case Document AM API: Implement 'Patch Document' API at case-document microservice
```
[ ] Yes
[ x] No
```

AM-509-test case added for Patch Document

---

build.gradle
src/main/java/uk/gov/hmcts/reform/ccd/document/am/controller/endpoints/CaseDocumentAm.java
src/main/java/uk/gov/hmcts/reform/ccd/document/am/service/impl/CaseDataStoreServiceImpl.java
src/main/java/uk/gov/hmcts/reform/ccd/document/am/service/impl/DocumentManagementServiceImpl.java
src/test/java/uk/gov/hmcts/reform/ccd/document/am/controller/advice/CaseDocumentControllerAdviceTest.java
src/test/java/uk/gov/hmcts/reform/ccd/document/am/service/impl/CaseDataStoreServiceImplTest.java
src/test/java/uk/gov/hmcts/reform/ccd/document/am/service/impl/DocumentManagementServiceImplTest.java

https://tools.hmcts.net/jira/browse/AM-581
- Code coverage with Junit tests
- Sonar scan smells addressed

Am 581 junit sonar coverage and code smells

---

.travis.yml
src/functionalTest/resources/features/F-000/F-000.feature
src/functionalTest/resources/features/F-000/S-000.td.json
src/functionalTest/resources/features/common/case_document/Common_Response_Body_Document_Base.td.json
src/main/java/uk/gov/hmcts/reform/ccd/document/am/apihelper/Constants.java
src/main/java/uk/gov/hmcts/reform/ccd/document/am/controller/endpoints/CaseDocumentAmController.java
src/main/java/uk/gov/hmcts/reform/ccd/document/am/service/impl/DocumentManagementServiceImpl.java
src/main/resources/application.yaml

Fixing the functional test case.

---

gradle/wrapper/gradle-wrapper.properties

For updating the gradle version from 5.5.1 to 5.6.1. There are many bumps which needs gradle 5.6.1 version.
[ ] No

Gradle version update

---

Jenkinsfile_CNP
charts/ccd-case-document-am-api/values.preview.template.yaml

Test branch to fix the DM store URL.
```
[ ] Yes
[x] No
```

Fixed the DM store URL.

---

src/functionalTest/resources/features/F-006/F-006.feature
src/main/java/uk/gov/hmcts/reform/ccd/document/am/controller/endpoints/CaseDocumentAm.java
src/main/java/uk/gov/hmcts/reform/ccd/document/am/controller/endpoints/CaseDocumentAmController.java
src/main/java/uk/gov/hmcts/reform/ccd/document/am/service/common/ValidationService.java
src/test/java/uk/gov/hmcts/reform/ccd/document/am/controller/endpoints/CaseDocumentAmControllerTest.java

https://tools.hmcts.net/jira/browse/AM-481

Am 481 implement get hashed token api

---

src/main/java/uk/gov/hmcts/reform/ccd/document/am/controller/endpoints/CaseDocumentAm.java
src/main/java/uk/gov/hmcts/reform/ccd/document/am/controller/endpoints/CaseDocumentAmController.java
src/main/java/uk/gov/hmcts/reform/ccd/document/am/model/UpdateDocumentCommand.java
src/main/java/uk/gov/hmcts/reform/ccd/document/am/service/DocumentManagementService.java
src/main/java/uk/gov/hmcts/reform/ccd/document/am/service/common/ValidationService.java
src/main/java/uk/gov/hmcts/reform/ccd/document/am/service/impl/DocumentManagementServiceImpl.java
src/test/java/uk/gov/hmcts/reform/ccd/document/am/controller/endpoints/CaseDocumentAmControllerTest.java
src/test/java/uk/gov/hmcts/reform/ccd/document/am/model/UpdateDocumentCommandTest.java
src/test/java/uk/gov/hmcts/reform/ccd/document/am/service/impl/DocumentManagementServiceImplTest.java

https://tools.hmcts.net/jira/browse/AM-509
Dev changes for Patch Document' API at case-document microservice
[ ] Yes
[ x] No

Am 509 patch ttl document api dev

---

src/main/java/uk/gov/hmcts/reform/ccd/document/am/service/common/ValidationService.java

https://tools.hmcts.net/jira/browse/AM-509
Dev changes for Patch Document' API at case-document microservice
[ ] Yes
[ x] No

AM-509 Patch TTL API - fixes

---

src/functionalTest/resources/features/F-000/S-000.td.json
src/main/java/uk/gov/hmcts/reform/ccd/document/am/service/impl/DocumentManagementServiceImpl.java

Updated the attach logic.

---

src/main/java/uk/gov/hmcts/reform/ccd/document/am/service/common/ValidationService.java
src/test/java/uk/gov/hmcts/reform/ccd/document/am/controller/endpoints/CaseDocumentAmControllerTest.java

https://tools.hmcts.net/jira/browse/AM-481
Changes based in Sumit's feedback.

AM-481 - validation fixes, null message for null inputs

---

src/main/java/uk/gov/hmcts/reform/ccd/document/am/service/impl/DocumentManagementServiceImpl.java

AM-609: Fixing code smell
```
[ ] Yes
[ ] No
```

Fixing the Sonar Vulnerability.

---

charts/ccd-case-document-am-api/values.preview.template.yaml
src/main/java/uk/gov/hmcts/reform/ccd/document/am/controller/endpoints/S2SAuthentication.java
src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/AM-620
Enable User Token
```
[ ] Yes
[ x] No
```

AM-620 Added IDAM_USER_URL for PR env.

---

src/main/java/uk/gov/hmcts/reform/ccd/document/am/apihelper/Constants.java
src/main/java/uk/gov/hmcts/reform/ccd/document/am/controller/endpoints/CaseDocumentAmController.java
src/main/java/uk/gov/hmcts/reform/ccd/document/am/service/common/ValidationService.java
src/main/java/uk/gov/hmcts/reform/ccd/document/am/service/impl/DocumentManagementServiceImpl.java
src/test/java/uk/gov/hmcts/reform/ccd/document/am/controller/endpoints/CaseDocumentAmControllerTest.java

https://tools.hmcts.net/jira/browse/AM-525
Fixed the minor issues with the response codes.
```
[ ] Yes
[ ] No
```

Am 525 upload document code fixes

---

src/main/java/uk/gov/hmcts/reform/ccd/document/am/controller/endpoints/CaseDocumentAmController.java

AM-516 fixes
```
[ ] Yes
[ ] No
```

Additional checks for inputs.

---

src/main/java/uk/gov/hmcts/reform/ccd/document/am/controller/endpoints/CaseDocumentAm.java
src/main/java/uk/gov/hmcts/reform/ccd/document/am/controller/endpoints/CaseDocumentAmController.java
src/test/java/uk/gov/hmcts/reform/ccd/document/am/controller/endpoints/CaseDocumentAmControllerTest.java

Added auth header to patchmetadata

---

build.gradle
src/main/java/uk/gov/hmcts/reform/ccd/document/am/Application.java
src/main/java/uk/gov/hmcts/reform/ccd/document/am/controller/WelcomeController.java
src/main/java/uk/gov/hmcts/reform/ccd/document/am/controller/endpoints/CaseDocumentAm.java
src/main/java/uk/gov/hmcts/reform/ccd/document/am/controller/endpoints/CaseDocumentAmController.java
src/main/java/uk/gov/hmcts/reform/ccd/document/am/controller/endpoints/S2SAuthentication.java
src/main/java/uk/gov/hmcts/reform/ccd/document/am/model/DocumentPayloadBody.java
src/main/java/uk/gov/hmcts/reform/ccd/document/am/model/StoredDocumentHalResourceCollection.java
src/main/java/uk/gov/hmcts/reform/ccd/document/am/service/DocumentManagementService.java
src/main/java/uk/gov/hmcts/reform/ccd/document/am/service/common/ValidationService.java
src/main/java/uk/gov/hmcts/reform/ccd/document/am/service/impl/CaseDataStoreServiceImpl.java
src/main/java/uk/gov/hmcts/reform/ccd/document/am/service/impl/DocumentManagementServiceImpl.java
src/main/java/uk/gov/hmcts/reform/ccd/document/am/util/ApplicationUtils.java
src/main/java/uk/gov/hmcts/reform/ccd/document/am/util/ResponseHelper.java
src/main/java/uk/gov/hmcts/reform/ccd/document/am/util/SecurityUtils.java
src/main/java/uk/gov/hmcts/reform/ccd/document/am/util/Swagger2SpringBoot.java
src/test/java/uk/gov/hmcts/reform/ccd/document/am/controller/WelcomeTest.java
src/test/java/uk/gov/hmcts/reform/ccd/document/am/model/DocumentPayloadBodyTest.java
src/test/java/uk/gov/hmcts/reform/ccd/document/am/model/ErrorMapTest.java
src/test/java/uk/gov/hmcts/reform/ccd/document/am/model/MetadataSearchCommandTest.java
src/test/java/uk/gov/hmcts/reform/ccd/document/am/service/common/ValidationServiceTest.java
src/test/java/uk/gov/hmcts/reform/ccd/document/am/service/impl/CaseDataStoreServiceImplTest.java
src/test/java/uk/gov/hmcts/reform/ccd/document/am/service/impl/DocumentManagementServiceImplTest.java

https://tools.hmcts.net/jira/browse/AM-609
Code smell and security issues as per Sonar
[ ] Yes
[ x] No

AM-609_Fix_Sonar_Issues

---

src/main/java/uk/gov/hmcts/reform/ccd/document/am/controller/endpoints/CaseDocumentAmController.java
src/main/java/uk/gov/hmcts/reform/ccd/document/am/service/impl/DocumentManagementServiceImpl.java

AM-481: Exception code alignment for hash-token api

---

src/test/java/uk/gov/hmcts/reform/ccd/document/am/service/impl/CaseDataStoreServiceImplTest.java
src/test/java/uk/gov/hmcts/reform/ccd/document/am/service/impl/DocumentManagementServiceImplTest.java

https://tools.hmcts.net/jira/browse/AM-628
Test cases needed updating to suit the new functionality.

Am-628 Test Case fixes

---

build.gradle
src/main/java/uk/gov/hmcts/reform/ccd/document/am/controller/endpoints/CaseDocumentAmController.java
src/main/java/uk/gov/hmcts/reform/ccd/document/am/service/common/ValidationService.java
src/main/java/uk/gov/hmcts/reform/ccd/document/am/util/Swagger2SpringBoot.java

https://tools.hmcts.net/jira/browse/AM-630
Fixing of existing Sonar issues and improving existing JUnit Coverage
[ ] Yes
[x] No

AM-630 : Fix Sonar Security Issues

---

src/main/java/uk/gov/hmcts/reform/ccd/document/am/service/impl/DocumentManagementServiceImpl.java
src/test/java/uk/gov/hmcts/reform/ccd/document/am/service/impl/DocumentManagementServiceImplTest.java

https://tools.hmcts.net/jira/browse/AM-629

AM-629 - added 'salt' like change to hash token for doc mgmt service

---

src/smokeTest/java/uk/gov/hmcts/reform/ccd/document/am/SmokeTest.java

Smoke test fix

---

.travis.yml
src/functionalTest/resources/features/F-006/S-064_Attach_Case_Id.td.json
src/functionalTest/resources/features/F-007/S-070.td.json
src/functionalTest/resources/features/F-007/S-071.td.json
src/functionalTest/resources/features/F-007/S-079.td.json
src/main/java/uk/gov/hmcts/reform/ccd/document/am/controller/advice/exception/ForbiddenException.java
src/main/java/uk/gov/hmcts/reform/ccd/document/am/controller/endpoints/CaseDocumentAmController.java
src/main/java/uk/gov/hmcts/reform/ccd/document/am/service/impl/DocumentManagementServiceImpl.java
src/test/java/uk/gov/hmcts/reform/ccd/document/am/service/impl/DocumentManagementServiceImplTest.java

Fix for attach API
```
[ ] Yes
[x] No
```

Attach api fix

---

src/integrationTest/java/uk/gov/hmcts/reform/ccd/document/am/config/SwaggerPublisher.java
src/main/java/uk/gov/hmcts/reform/ccd/document/am/Application.java
src/main/java/uk/gov/hmcts/reform/ccd/document/am/controller/endpoints/CaseDocumentAmController.java
src/main/java/uk/gov/hmcts/reform/ccd/document/am/service/impl/DocumentManagementServiceImpl.java
src/main/java/uk/gov/hmcts/reform/ccd/document/am/util/ResponseHelper.java
src/test/java/uk/gov/hmcts/reform/ccd/document/am/controller/endpoints/CaseDocumentAmControllerTest.java
src/test/java/uk/gov/hmcts/reform/ccd/document/am/model/StoredDocumentHalResourceCollectionTest.java
src/test/java/uk/gov/hmcts/reform/ccd/document/am/service/impl/DocumentManagementServiceImplTest.java

https://tools.hmcts.net/jira/browse/AM-425

AM-425 - removed unnecessary suppressions

---

src/test/java/uk/gov/hmcts/reform/ccd/document/am/service/common/ValidationServiceTest.java
src/test/java/uk/gov/hmcts/reform/ccd/document/am/service/impl/DocumentManagementServiceImplTest.java

Removed unused test case
Added new tests for hashtoken API
refactored code.

AM-553 : JUnit tests - new tests and code refactoring

---

Jenkinsfile_CNP
src/functionalTest/java/uk/gov/hmcts/ccd/documentam/befta/CaseDocumentAmTestAutomationAdapter.java

xui_webapp env variables for PR
```
[ ] Yes
[x] No
```

xui_webapp env variables

---

src/functionalTest/resources/features/common/case/befta-jurisdiction2-case-creation/Befta_Jurisdiction2_Case_Creation_Base_Data.td.json

Header update to v3.0
```
[ ] Yes
[ ] No
```

Headers update as per changes in PR-905

---

src/main/java/uk/gov/hmcts/reform/ccd/document/am/service/impl/DocumentManagementServiceImpl.java
src/test/java/uk/gov/hmcts/reform/ccd/document/am/service/impl/DocumentManagementServiceImplTest.java

Create case header fix

---

src/main/resources/service_config.json

Am-588: Temp checkin. DO NOT MERGE

---

charts/ccd-case-document-am-api/values.aat.template.yaml

Master: Fix for the smoke tests.

---

src/smokeTest/java/uk/gov/hmcts/reform/ccd/document/am/SmokeTest.java

Master: Enabling the smoke tests.

---

charts/ccd-case-document-am-api/Chart.yaml

Master: Updating the chart version.

---

charts/ccd-case-document-am-api/Chart.yaml
charts/ccd-case-document-am-api/values.aat.template.yaml
charts/ccd-case-document-am-api/values.preview.template.yaml
charts/ccd-case-document-am-api/values.yaml

Updating the chart version.

---

Jenkinsfile_CNP

AAT Deployemnt fixes.
```
[ ] Yes
[ ] No
```

updating the Jenkins file.

---

Jenkinsfile_CNP

Health check fixes

---

charts/ccd-case-document-am-api/Chart.yaml

https://tools.hmcts.net/jira/browse/AM-750
```
[ ] Yes
[ ] No
```

Bumping the chart version.

---

Jenkinsfile_CNP
config/owasp/suppressions.xml

disabling the installCharts goal.

---

src/main/java/uk/gov/hmcts/reform/ccd/document/am/configuration/SwaggerConfiguration.java

removing unnecessary fields in swagger

---

.gitignore
Jenkinsfile_CNP
build.gradle

https://tools.hmcts.net/jira/browse/RDM-9342
```
[ ] Yes
[ ] No
```

RDM-9342: Split reports for smoke and functional tests

---

charts/ccd-case-document-am-api/Chart.yaml

upgrade base chart version
```
[ ] Yes
[X] No
```

upgrade base chart version

---

charts/ccd-case-document-am-api/Chart.yaml
config/owasp/suppressions.xml

Upgrade java chart version and cleanup CVE suppressions that are no more applicable.
```
[ ] Yes
[X] No
```

Upgrade java chart version and cleanup redundant CVE suppressions

---

build.gradle
config/owasp/suppressions.xml

Reverts hmcts/ccd-case-document-am-api#373

Revert "RDM-11454 fix CVE-2021-22112 +(use hmcts plugin)"

---

build.gradle
src/integrationTest/java/uk/gov/hmcts/reform/ccd/documentam/BaseTest.java
src/integrationTest/java/uk/gov/hmcts/reform/ccd/documentam/config/SwaggerPublisher.java
src/integrationTest/resources/integration-test.properties
src/integrationTest/resources/wiremock-stubs/idam/openid_config.json
src/test/java/uk/gov/hmcts/reform/ccd/documentam/TestIdamConfiguration.java

RDM-11001 - fixed swagger publisher and Integration setup

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/RDM-11454
CVE-2021-22112 (CCD Case Document AM API)
```
[ ] Yes
[X] No
```

RDM-11454 CCD Case Document AM API

---

config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/RDM-11765
Update CVE Suppress Until Date In All Services
```
[ ] Yes
[X] No
```

RDM-11765 Update CVE Suppress Until Date In All Services

---

build.gradle
src/functionalTest/java/uk/gov/hmcts/ccd/documentam/befta/CaseDocumentAmTestAutomationAdapter.java
src/functionalTest/java/uk/gov/hmcts/ccd/documentam/befta/TestDataLoaderMain.java

https://tools.hmcts.net/jira/browse/RDM-11783
Fix Broken Master Build
```
[ ] Yes
[X] No
```

RDM-11783 Fix Broken Master Build

---

build.gradle

https://tools.hmcts.net/jira/browse/RDM-11831
Fix alternate Failures Case Doc AM Master Build
```
[ ] Yes
[X] No
```

RDM-11831 Fix alternate Failures Case Doc AM Master Build

---

config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/RDM-12131
Extend Expiry Dates of All CVE Suppressions in CCD Repos
```
[ ] Yes
[X] No
```

RDM-12131 Extend Expiry Dates of All CVE Suppressions in CCD Repos

---

charts/ccd-case-document-am-api/Chart.yaml

Upgrade Base Chart Versions (Java & Nodejs)
Upgrade Base Chart Versions (Java & Nodejs)
```
[ ] Yes
[X] No
```

RDM-12054 Upgrade Base Chart Versions (Java & Nodejs)

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/RDM-12199?filter=-1
CVE-2021-29425 (Case Document AM API)
```
[ ] Yes
[X] No
```

RDM-12199 CVE-2021-29425 (Case Document AM API)

---

src/main/java/uk/gov/hmcts/reform/ccd/documentam/service/impl/DocumentManagementServiceImpl.java

https://tools.hmcts.net/jira/browse/RDM-12108?filter=-1
Fortify Issue 13442331 - Unreleased Resource: Streams - High
```
[ ] Yes
[X] No
```

RDM-12108 Fortify Issue 13442331 - Unreleased Resource: Streams - High

---

build.gradle

https://tools.hmcts.net/jira/browse/RDM-9765
Bump up BEFTA Fw version for RDM-9765.
```
[ ] Yes
[X] No
```

RDM-9765 Added jit pack and befta code changes

---

Jenkinsfile_CNP
charts/ccd-case-document-am-api/Chart.yaml
charts/ccd-case-document-am-api/values.aat.template.yaml
charts/ccd-case-document-am-api/values.preview.template.yaml
charts/ccd-case-document-am-api/values.yaml
config/owasp/suppressions.xml
docker-compose.yml
lib/AI-Agent.xml
src/functionalTest/resources/features/F-001/F-001.feature
src/functionalTest/resources/features/F-002/F-002.feature
src/functionalTest/resources/features/common/case/befta-jurisdiction2-case-creation/Befta_Jurisdiction2_Default_Full_Case_Response_Single_Document.td.json
src/main/java/uk/gov/hmcts/reform/ccd/documentam/configuration/SwaggerConfiguration.java
src/main/resources/application.yaml

RDM-11396 - data-store wiring and cleanup

---

charts/ccd-case-document-am-api/Chart.yaml
charts/ccd-case-document-am-api/values.yaml

wiring fix

---

config/owasp/suppressions.xml

updated suppress Until Date for false positives

---

src/integrationTest/java/uk/gov/hmcts/reform/ccd/documentam/controller/CaseDocumentAmControllerIT.java
src/main/java/uk/gov/hmcts/reform/ccd/documentam/apihelper/Constants.java
src/main/java/uk/gov/hmcts/reform/ccd/documentam/controller/endpoints/CaseDocumentAmController.java
src/main/java/uk/gov/hmcts/reform/ccd/documentam/service/DocumentManagementService.java
src/main/java/uk/gov/hmcts/reform/ccd/documentam/service/impl/DocumentManagementServiceImpl.java
src/test/java/uk/gov/hmcts/reform/ccd/documentam/controller/endpoints/CaseDocumentAmControllerTest.java
src/test/java/uk/gov/hmcts/reform/ccd/documentam/service/impl/DocumentManagementServiceImplTest.java

Method rename - 263e8fdffa04b492b6945a46b5d95a00a9749bed
bug fix with tests - 15a6432e3e999f6b5b6f35bdd75f1b746a57c744
constants clean up - 522b82c73c043bdbb8dedaa797594f26c15599e8
```
[ ] Yes
[ x] No
```

CCD-1343- Missing MetaData when reaching case-doc-am-api

---

src/main/resources/service_config.json

added sscs to service config

---

charts/ccd-case-document-am-api/Chart.yaml
charts/ccd-case-document-am-api/values.yaml

removed data-store PR reference and added sscs to s2s

---

build.gradle
src/integrationTest/java/uk/gov/hmcts/reform/ccd/documentam/controller/CaseDocumentAmControllerIT.java
src/integrationTest/java/uk/gov/hmcts/reform/ccd/documentam/fixtures/WiremockFixtures.java
src/main/java/uk/gov/hmcts/reform/ccd/documentam/client/dmstore/DmUploadResponse.java
src/main/java/uk/gov/hmcts/reform/ccd/documentam/controller/endpoints/CaseDocumentAmController.java
src/main/java/uk/gov/hmcts/reform/ccd/documentam/model/Document.java
src/main/java/uk/gov/hmcts/reform/ccd/documentam/model/UploadResponse.java
src/main/java/uk/gov/hmcts/reform/ccd/documentam/service/DocumentManagementService.java
src/main/java/uk/gov/hmcts/reform/ccd/documentam/service/impl/DocumentManagementServiceImpl.java
src/test/java/uk/gov/hmcts/reform/ccd/documentam/controller/endpoints/CaseDocumentAmControllerTest.java
src/test/java/uk/gov/hmcts/reform/ccd/documentam/service/impl/DocumentManagementServiceImplTest.java

fixing upload links 

---

src/integrationTest/java/uk/gov/hmcts/reform/ccd/documentam/fixtures/WiremockFixtures.java
src/main/java/uk/gov/hmcts/reform/ccd/documentam/model/UpdateDocumentsCommand.java
src/main/java/uk/gov/hmcts/reform/ccd/documentam/service/impl/DocumentManagementServiceImpl.java
src/test/java/uk/gov/hmcts/reform/ccd/documentam/service/impl/DocumentManagementServiceImplTest.java

https://tools.hmcts.net/jira/browse/RDM-12558
Remove TTL on document when meta-data is updated
```
[ ] Yes
[x] No
```

RDM-12558 - Remove TTL on document when meta-data is updated

---

src/main/java/uk/gov/hmcts/reform/ccd/documentam/service/impl/DocumentManagementServiceImpl.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/ccd/documentam/service/impl/DocumentManagementServiceImplTest.java

configured document ttl default value as 7 days

---

Jenkinsfile_nightly
build.gradle
config/fortify-client.properties

https://tools.hmcts.net/jira/browse/CCD-1588
fortify implementation
```
[ ] Yes
[x] No
```

CCD-1588 - fortify implementation

---

src/main/java/uk/gov/hmcts/reform/ccd/documentam/controller/endpoints/CaseDocumentAmController.java
src/main/resources/application.yaml

added a flag to to control rest api endpoints

---

src/main/resources/application.yaml

added few divorce case types to the moving list

---

src/main/java/uk/gov/hmcts/reform/ccd/documentam/configuration/ApplicationConfiguration.java
src/main/resources/application.yaml

http timeout configs

---

src/integrationTest/java/uk/gov/hmcts/reform/ccd/documentam/controller/CaseDocumentAmControllerIT.java
src/main/java/uk/gov/hmcts/reform/ccd/documentam/service/impl/DocumentManagementServiceImpl.java
src/main/resources/service_config.json

Service config clean up

---

src/integrationTest/java/uk/gov/hmcts/reform/ccd/documentam/controller/CaseDocumentAmControllerIT.java
src/main/java/uk/gov/hmcts/reform/ccd/documentam/service/impl/DocumentManagementServiceImpl.java
src/main/resources/service_config.json

Reverts hmcts/ccd-case-document-am-api#456

Revert "Service config clean up"

---

src/functionalTest/resources/features/F-003/F-003_Test_Data_Base.td.json
src/functionalTest/resources/features/F-005/F-005_Test_Data_Base.td.json
src/integrationTest/java/uk/gov/hmcts/reform/ccd/documentam/controller/CaseDocumentAmControllerIT.java
src/main/java/uk/gov/hmcts/reform/ccd/documentam/service/impl/DocumentManagementServiceImpl.java
src/main/resources/service_config.json

Reverts hmcts/ccd-case-document-am-api#457

Revert "Revert "Service config clean up""

---

src/functionalTest/resources/features/F-001/S-001.td.json
src/functionalTest/resources/features/F-006/S-064_Attach_Case_Id.td.json
src/functionalTest/resources/features/F-007/F-007_Test_Data_Base.td.json
src/functionalTest/resources/features/F-007/S-102.td.json
src/functionalTest/resources/features/F-007/S-103.td.json
src/functionalTest/resources/features/F-007/S-104.td.json
src/functionalTest/resources/features/common/case_document/Common_Response_Body_Document_Base.td.json
src/integrationTest/java/uk/gov/hmcts/reform/ccd/documentam/controller/CaseDocumentAmControllerIT.java
src/main/java/uk/gov/hmcts/reform/ccd/documentam/apihelper/Constants.java
src/main/java/uk/gov/hmcts/reform/ccd/documentam/client/dmstore/DocumentStoreClient.java
src/main/java/uk/gov/hmcts/reform/ccd/documentam/model/Document.java
src/main/java/uk/gov/hmcts/reform/ccd/documentam/service/impl/DocumentManagementServiceImpl.java
src/test/java/uk/gov/hmcts/reform/ccd/documentam/service/impl/DocumentManagementServiceImplTest.java

Fixing metadata names to inline with DM store

---

src/functionalTest/resources/features/F-001/F-001.feature
src/functionalTest/resources/features/F-002/F-002.feature

Temporary ignore

---

src/functionalTest/resources/features/F-001/F-001.feature
src/functionalTest/resources/features/F-002/F-002.feature

Reverts hmcts/ccd-case-document-am-api#460

Revert "Temporary ignore"

---

src/main/java/uk/gov/hmcts/reform/ccd/documentam/ApplicationParams.java
src/main/java/uk/gov/hmcts/reform/ccd/documentam/service/impl/DocumentManagementServiceImpl.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/ccd/documentam/service/impl/DocumentManagementServiceImplTest.java

added employment case types to moving list. Improved logging

---

Jenkinsfile_CNP
charts/ccd-case-document-am-api/values.aat.template.yaml
charts/ccd-case-document-am-api/values.preview.template.yaml
src/main/java/uk/gov/hmcts/reform/ccd/documentam/service/impl/DocumentManagementServiceImpl.java

Added some logging. Preview wiring.

---

config/owasp/suppressions.xml
src/main/resources/service_config.json

iac config

---

config/owasp/suppressions.xml

Suppress CVE-2021-22119
```
[ ] Yes
[ ] No
```

Suppress CVE-2021-22119

---

charts/ccd-case-document-am-api/Chart.yaml
charts/ccd-case-document-am-api/values.yaml

whitelisted probate and iac

---

charts/ccd-case-document-am-api/Chart.yaml
charts/ccd-case-document-am-api/values.yaml
src/main/resources/application.yaml
src/main/resources/service_config.json

https://tools.hmcts.net/jira/browse/EM-3667
Updated CDAM config for Redaction API
```
[ ] Yes
[X] No
```

Updated CDAM config for Redaction API

---

charts/ccd-case-document-am-api/Chart.yaml
charts/ccd-case-document-am-api/values.yaml
src/main/resources/application.yaml
src/main/resources/service_config.json

https://tools.hmcts.net/jira/browse/EM-3669
Updated CDAM config for Docassembly API
```
[ ] Yes
[X] No
```

Updated CDAM config for Docassembly API

---

src/integrationTest/java/uk/gov/hmcts/reform/ccd/documentam/BaseTest.java
src/integrationTest/java/uk/gov/hmcts/reform/ccd/documentam/controller/CaseDocumentAmControllerIT.java
src/main/java/uk/gov/hmcts/reform/ccd/documentam/auditlog/aop/AuditAspect.java

https://tools.hmcts.net/jira/browse/RDM-12771
ix upload endpoint logging and update tests
```
[ ] Yes
[x] No
```

RDM-12771 - fix upload endpoint audit logging and update tests

---

build.gradle
config/owasp/suppressions.xml

Resolve CVE-2021-28170
```
[ ] Yes
[x] No
```

CCD-1879 Resolve CVE-2021-28170

---

charts/ccd-case-document-am-api/Chart.yaml
charts/ccd-case-document-am-api/values.yaml
src/main/resources/application.yaml
src/main/resources/service_config.json

https://tools.hmcts.net/jira/browse/CCD-1940
```
[ ] Yes
[X] No
```

CCD-1940 : updated caseTypeId as requested

---

charts/ccd-case-document-am-api/Chart.yaml
charts/ccd-case-document-am-api/values.yaml
src/main/resources/service_config.json

https://tools.hmcts.net/jira/browse/EM-3668
Updated CDAM config for Stitching API
```
[ ] Yes
[X] No
```

Updated CDAM config for Stitching API

---

charts/ccd-case-document-am-api/Chart.yaml
charts/ccd-case-document-am-api/values.yaml
src/main/resources/application.yaml
src/main/resources/service_config.json

Duplicate of https://github.com/hmcts/ccd-case-document-am-api/pull/483

Added cmc_claim_store to config

---

config/owasp/suppressions.xml

CCD-1993 (https://tools.hmcts.net/jira/browse/CCD-1993)
Updated CVE suppression dates in suppressions.xml to 25/10/2021
```
[ ] Yes
[x] No
```

Updated CVE suppression dates in suppressions.xml to 25/10/2021

---

src/functionalTest/resources/features/F-007/F-007-Attach_Document1.td.json
src/functionalTest/resources/features/F-007/F-007.feature
src/functionalTest/resources/features/F-007/S-078.td.json
src/integrationTest/java/uk/gov/hmcts/reform/ccd/documentam/controller/CaseDocumentAmControllerIT.java
src/main/java/uk/gov/hmcts/reform/ccd/documentam/service/impl/DocumentManagementServiceImpl.java
src/test/java/uk/gov/hmcts/reform/ccd/documentam/service/impl/DocumentManagementServiceImplTest.java

Handle duplicate requests for metadata update

---

README.md
charts/ccd-case-document-am-api/Chart.yaml
charts/ccd-case-document-am-api/values.yaml
src/functionalTest/resources/features/F-006/F-006.feature
src/main/resources/application.yaml
src/main/resources/service_config.json

https://tools.hmcts.net/jira/browse/CCD-2125
bulk_scan_orchestrator has been created with HASHCODE permission
```
[ ] Yes
[x] No
```

created bulk_scan_orchestrator with HASHCODE permission

---

charts/ccd-case-document-am-api/Chart.yaml
charts/ccd-case-document-am-api/values.yaml
src/main/resources/service_config.json

https://tools.hmcts.net/jira/browse/ECM-146
https://tools.hmcts.net/jira/browse/CCD-2159
Added ETHOS service to charts and service config
```
[ ] Yes
[ ] No
```

ECM-146 - Added Ethos service

---

charts/ccd-case-document-am-api/Chart.yaml
charts/ccd-case-document-am-api/values.yaml
src/main/resources/service_config.json

[CCD-2170](https://tools.hmcts.net/jira/browse/CCD-2170)
Add divorce services to CCD case am
```
[ ] Yes
[ x] No
```

CCD-2170: Add divorce services to CCD case am

---

charts/ccd-case-document-am-api/Chart.yaml
charts/ccd-case-document-am-api/values.yaml
src/main/resources/service_config.json

https://tools.hmcts.net/jira/browse/CCD-2260
https://tools.hmcts.net/jira/browse/DFPL-29
Add fpl_case_service to charts + configs 
```
[ ] Yes
[X] No
```

CCD-2260: Add FPL case service to CDAM

---

src/main/resources/service_config.json

CCD-2170: Add FR update role

---

src/main/resources/service_config.json

https://tools.hmcts.net/jira/browse/CCD-2377
Added PRL services
```
[ ] Yes
[x] No
```

CCD-2377: Adding PRL service to service_config.json in case-document-am-api

---

src/main/resources/application.yaml
src/main/resources/service_config.json

https://tools.hmcts.net/jira/browse/CCD-2367
```
[ ] Yes
[ ] No
```

added a new Employment Tribunal service

---

charts/ccd-case-document-am-api/Chart.yaml
charts/ccd-case-document-am-api/values.yaml

https://tools.hmcts.net/jira/browse/CCD-2367
et_cos was whitelisted
```
[ ] Yes
[ ] No
```

et_cos whitelisted

---

charts/ccd-case-document-am-api/Chart.yaml
charts/ccd-case-document-am-api/values.yaml

https://tools.hmcts.net/jira/browse/CCD-2399
```
[ ] Yes
[ ] No
```

added prl_cos_api, prl_dgs_api to whitelist

---

src/main/resources/application.yaml
src/main/resources/service_config.json

https://tools.hmcts.net/jira/browse/CCD-2398
```
[ ] Yes
[ ] No
```

additional permission for ethos_repl_docmosis_service

---

Jenkinsfile_CNP
build.gradle
src/functionalTest/java/uk/gov/hmcts/ccd/documentam/befta/CaseDocumentAmTestAutomationAdapter.java
src/functionalTest/java/uk/gov/hmcts/ccd/documentam/befta/TestDataLoaderMain.java

https://tools.hmcts.net/jira/browse/CCD-2451
Removing jcenter due to [shutdown](https://blog.gradle.org/jcenter-shutdown)
```
[ ] Yes
[ x] No
```

Update to build.gradle

---

config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-2584
Suppressing CVE-2021-22060
```
[ ] Yes
[X ] No
```

Suppressing CVE-2021-22060 with added notes

---

config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-2692
CWE-862 Suppression
```
[ ] Yes
[ X] No
```

CWE-862 Suppression

---

charts/ccd-case-document-am-api/Chart.yaml

helm chart update

---

build.gradle

https://tools.hmcts.net/jira/browse/CCD-2718
```
[ ] Yes
[ ] No
```

test definition version update to 7.13.0

---

charts/ccd-case-document-am-api/Chart.yaml

Upgrade to Latest Base Helm Charts

---

src/main/java/uk/gov/hmcts/reform/ccd/documentam/controller/endpoints/CaseDocumentAmController.java
src/main/java/uk/gov/hmcts/reform/ccd/documentam/model/AuthorisedService.java
src/main/java/uk/gov/hmcts/reform/ccd/documentam/service/DocumentManagementService.java
src/main/java/uk/gov/hmcts/reform/ccd/documentam/service/impl/DocumentManagementServiceImpl.java
src/main/resources/service_config.json
src/test/java/uk/gov/hmcts/reform/ccd/documentam/controller/endpoints/CaseDocumentAmControllerTest.java
src/test/java/uk/gov/hmcts/reform/ccd/documentam/service/impl/DocumentManagementServiceImplTest.java

https://tools.hmcts.net/jira/browse/CCD-2518
```
[ ] Yes
[x] No
```

added optional caseTypeId for hashtoken calculation

---

src/main/resources/service_config.json

https://tools.hmcts.net/jira/browse/CCD-2819
Added Employment Tribunal service security config
```
[ ] Yes
[X] No
```

Added Employment Tribunal service

---

build.gradle
config/owasp/suppressions.xml
src/integrationTest/java/uk/gov/hmcts/reform/ccd/documentam/wiremock/extension/DynamicOAuthJwkSetResponseTransformer.java

https://tools.hmcts.net/jira/browse/CCD-2692
Fixing CWE-862
```
[ ] Yes
[X ] No
```

Change version to 5.6.1 and remove suppression

---

config/owasp/suppressions.xml

-Adding Suppression for Spring Beans jar. Temporary Fix.

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-2922
```
[ ] Yes
[ ] No
```

spring framework version update to 5.3.15

---

src/main/resources/service_config.json

https://tools.hmcts.net/jira/browse/CCD-2933
```
[ ] Yes
[ ] No
```

added service config for ds_ui

---

config/owasp/suppressions.xml

-
Temp suppression
```
[ ] Yes
[X] No
```

suppress new CVE

---

config/owasp/suppressions.xml

Suppresion for spring-core-5.3.18.jar relate dependency check failure.
```
[ ] Yes
[x ] No
```

Spring-core-5.3.18 dependency issue suppression

---

src/main/java/uk/gov/hmcts/reform/ccd/documentam/client/dmstore/DocumentStoreClient.java
src/main/java/uk/gov/hmcts/reform/ccd/documentam/service/impl/DocumentManagementServiceImpl.java
src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/CCD-3022
```
[ ] Yes
[ ] No
```

additional logs for debugging

---

src/main/java/uk/gov/hmcts/reform/ccd/documentam/service/DocumentManagementService.java
src/main/java/uk/gov/hmcts/reform/ccd/documentam/service/impl/DocumentManagementServiceImpl.java
src/test/java/uk/gov/hmcts/reform/ccd/documentam/service/impl/DocumentManagementServiceImplTest.java

https://tools.hmcts.net/jira/browse/CCD-2802
```
[ ] Yes
[ ] No
```

implemented patch metadata operation into generate hashtoken flow

---

src/functionalTest/resources/features/F-001/F-001.feature
src/functionalTest/resources/features/F-002/F-002.feature
src/main/resources/service_config.json

https://tools.hmcts.net/jira/browse/CCD-3186
```
[ ] Yes
[ ] No
```

add READ permission to ccd_data

---

src/functionalTest/resources/features/common/case/Citizen_Full_Case_Creation_Data.td.json
src/functionalTest/resources/features/common/case/Citizen_Token_Creation_Data_For_Case_Creation.td.json
src/functionalTest/resources/features/common/case/befta-jurisdiction2-case-creation/Befta_Jurisdiction2_Citizen_Case_Creation_Data.td.json
src/functionalTest/resources/features/common/case/befta-jurisdiction2-case-creation/Befta_Jurisdiction2_Citizen_Token_Creation_Data.td.json
src/functionalTest/resources/features/common/case/befta-jurisdiction2-case-creation/Befta_Jurisdiction2_Token_For_Update_Case.td.json
src/functionalTest/resources/features/common/case/befta-jurisdiction2-case-creation_by_solicitor_1/Befta_Jurisdiction2_Default_Full_Case_Creation_Data_solicitor_1.td.json
src/functionalTest/resources/features/common/case/befta-jurisdiction2-case-creation_by_solicitor_1/Befta_Jurisdiction2_Default_Token_Creation_Data_For_Case_Creation_Solicitor_1.td.json
src/functionalTest/resources/features/common/case/befta-jurisdiction2-citizen-case-creation/Befta_Jurisdiction2_Default_Citizen_Case_Creation_Data.td.json
src/functionalTest/resources/features/common/case/befta-jurisdiction2-citizen-case-creation/Befta_Jurisdiction2_Default_Token_Creation_Data_For_Citizen_Case_Creation.td.json
src/functionalTest/resources/features/common/case/befta_new/Befta_Default_Full_Case_Creation_Data.td.json
src/functionalTest/resources/features/common/case/befta_new/Befta_Default_Token_Creation_Data_For_Case_Creation.td.json

https://tools.hmcts.net/jira/browse/CCD-2972
There are misusages of hardcoded passwords which are causing fortify vulnerabilities.
```
[ ] Yes
[ x] No
```

CCD-2972: Fortify vulnerabilities fix

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-3291
Removed suppressions and updated spring-framework.version to 5.3.20
```
[ ] Yes
[X] No
```

Removed suppressions and updated spring-framework.version to 5.3.20

---

src/main/resources/service_config.json

https://tools.hmcts.net/jira/browse/CCD-3313
```
[ ] Yes
[ ] No
```

added fis_cos_api service configurations

---

src/main/resources/service_config.json

https://tools.hmcts.net/jira/browse/CCD-3363
Whitelist prl_citizen_frontend service in case-document-am-api
**Does this PR introduce a breaking change?**
```
[ ] Yes
[x] No
```

CCD-3363: Whitelist prl_citizen_frontend service in case-document-am-api

---

config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-3447
CCD-3447 : Update suppressions.xml (CVE-2022-33915)
```
[ ] Yes
[X] No
```

CCD-3447 : Update suppressions.xml (CVE-2022-33915)

---

config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-3447
False positive.   CVE-2022-33915 (cpe;2.3;a;apache;log4j) only impacts AWS Log4j hotpatch , and not general Log4j build.   See Jira ticket.
**Does this PR introduce a breaking change?**
```
[ ] Yes
[x] No
```

CCD-3447: CVE-2022-33915 ccd-case-document-am-api

---

charts/ccd-case-document-am-api/Chart.yaml

https://tools.hmcts.net/jira/browse/CCD-3434
Upgrade java, postgresql and redis configurations
```
[ ] Yes
[x] No
```

CCD-3434 upgrade Java, postgresql and redis configurations

---

Jenkinsfile_CNP
charts/ccd-case-document-am-api/values.preview.template.yaml
src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/CCD-3597
Secret Rotated in KV, removing and deployment changes
```
[ ] Yes
[x] No
```

Update application.yaml CCD-3597

---

config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-3577
Cleanup CVE Suppressions
```
[ ] Yes
[x ] No
```

Ccd 3577 cleanup CVE suppressions

---

src/main/resources/service_config.json

https://tools.hmcts.net/jira/browse/CCD-3712
```
[ ] Yes
[ ] No
```

CCD-3712 - add case type BAIL to iac

---

config/owasp/suppressions.xml

added suppression

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-3522
https://tools.hmcts.net/jira/browse/CCD-3523
https://tools.hmcts.net/jira/browse/CCD-3776
fixed
```
[ ] Yes
[x] No
```

CCD-3532-3533: Added fix for CVE-2022-22970 CVE-2022-22971 CVE-2022-42003 and CVE-2022-42004

---

charts/ccd-case-document-am-api/values.yaml
docker-compose.yml
src/main/resources/application.yaml
src/main/resources/service_config.json

https://tools.hmcts.net/jira/browse/CCD-3885
```
[ ] Yes
[ ] No
```

CCD-3885 whitelist nfdiv backend and frontend

---

.github/workflows/dependency-check.yml

Fixed invalid attribute value

---

.gitignore
build.gradle

https://tools.hmcts.net/jira/browse/CCD-3829
Add Gradle runRemoteDemo() task.
See Jira ticket for command used to add Azure secret named ‘case-document-am-api-remote-env’.
**Does this PR introduce a breaking change?**
```
[ ] Yes
[x] No
```

CCD-3829: Add Gradle runRemoteDemo() task

---

src/main/resources/service_config.json

https://tools.hmcts.net/jira/browse/CCD-4048
```
[ ] Yes
[ ] No
```

ST_CIC service configuration

---

charts/ccd-case-document-am-api/values.yaml
src/main/resources/service_config.json

https://tools.hmcts.net/jira/browse/CCD-4092
```
[ ] Yes
[ ] No
```

Special Tribunals service configuration

---

config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-4157
Update suppressions.xml
```
[ ] Yes
[ ] No
```

CCD-4157: Update suppressions.xml

---

charts/ccd-case-document-am-api/Chart.yaml

https://tools.hmcts.net/jira/browse/CCD-4317
Upgrade base charts
```
[ ] Yes
[X] No
```

CCD-4317 Upgrade base charts

---

build.gradle
src/test/java/uk/gov/hmcts/reform/ccd/documentam/security/SecurityUtilsTest.java

https://tools.hmcts.net/jira/browse/CCD-4408
```
[ ] Yes
[ ] No
```

update befta-fw version to 8.7.11

---

.github/workflows/swagger.yml
README.md

https://tools.hmcts.net/jira/browse/CCD-4476
CCD-4476 : changed reform-api-docs to cnp-api-docs
```
[ ] Yes
[X] No
```

CCD-4476 : changed reform-api-docs to cnp-api-docs

---

src/main/resources/service_config.json

https://tools.hmcts.net/jira/browse/CCD-4770
```
[ ] Yes
[ ] No
```

add UPDATE permission to civil_service

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-4737
CCD-4737 : Fix CVE-2023-28709 (Bumped version of Tomcat)
```
[ ] Yes
[X] No
```

CCD-4737 : Fix CVE-2023-28709 (Bumped version of Tomcat)

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-4479
CCD-4479 : Fix for CVE-2023-20861 - upgrade Spring Framework version to 5.3.26
```
[ ] Yes
[X] No
```

CCD-4454 : CVE-2022-1471-Fix

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/secure/RapidBoard.jspa?rapidView=1382&projectKey=CCD&view=detail&selectedIssue=CCD-4736
Removing https://github.com/advisories/GHSA-xf96-w227-r7c4 suppression and bumping to the next minor version change.
```
[ ] Yes
[x] No
```

Removing suppression and bumping packages

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-4584
Fix CVE-2023-20863
```
[ ] Yes
[x ] No
```

Fix CVE-2023-20863

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-5201
Updated Spring Security to resolve CVE.
```
[ ] Yes
[X] No
```

CCD-5201 CVE fixes

---

build.gradle

fix Fortify gradle task

---

build.gradle

https://tools.hmcts.net/jira/browse/CCD-5825
Fix fortify client library 
```
[ ] Yes
[X] No
```

Fix nightly

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-5158
Upgrade Tomcat to fix CVE
```
[ ] Yes
[x] No
```

CCD-5158 Fix CVE-2023-46589

---

config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-5265
CVE-2023-1370 has already been fixed, but suppression was not removed
```
[ ] Yes
[X] No
```

CCD-5265 : Remove suppression

---

build.gradle

enable functional test reports in pipeline

---

.github/workflows/dependency-check.yml
.github/workflows/swagger.yml
Dockerfile
README.md
acb.tpl.yaml
build.gradle
charts/ccd-case-document-am-api/Chart.yaml

https://tools.hmcts.net/jira/browse/CME-42
Bump java to version 21
```
[ ] Yes
[x] No
```

CME-42 Bump java to version 21

---

src/main/resources/service_config.json

https://tools.hmcts.net/jira/browse/CIV-16248
```
[ ] Yes
[ ] No
```

CIV-16248 added general application in civil service config

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-5923
removed suppression, bumped jackson
```
[ ] Yes
[X] No
```

CCD-5923 : Fix CVE-2023-35116

---

infrastructure/state.tf

https://tools.hmcts.net/jira/browse/CME-310
```
[ ] Yes
[x ] No
```

CME-310: Update azurerm

---

.github/workflows/dependency-check.yml
.github/workflows/swagger.yml

https://tools.hmcts.net/jira/browse/CCD-6098
```
[ ] Yes
[ ] No
```

CCD-6098 update cache to v4

---

config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/CCD-6132
Removed CVE suppression
```
[ ] Yes
[x] No
```

Fix CVE-2023-6378:

---

charts/ccd-case-document-am-api/Chart.yaml

https://tools.hmcts.net/jira/browse/CCD-6193
```
[ ] Yes
[ ] No
```

CCD-6193 update chart version

---

config/owasp/suppressions.xml

CVE-2024-38820 refer [https://tools.hmcts.net/jira/browse/CCD-6278]
CVE-2025-24813 refer [https://tools.hmcts.net/jira/browse/CCD-6283]
Suppressed CVE
```
[ ] Yes
[x] No
```

CCD-6278 : Suppress CVE 38820

---

src/test/java/uk/gov/hmcts/reform/ccd/documentam/client/dmstore/DocumentStoreClientTest.java

add new test cases for DocumentStoreClient

---

src/main/java/uk/gov/hmcts/reform/ccd/documentam/client/dmstore/DocumentStoreClient.java
src/main/java/uk/gov/hmcts/reform/ccd/documentam/controller/advice/CaseDocumentControllerAdvice.java
src/main/java/uk/gov/hmcts/reform/ccd/documentam/controller/advice/HttpClientExceptionWrapper.java
src/test/java/uk/gov/hmcts/reform/ccd/documentam/client/dmstore/DocumentStoreClientTest.java
src/test/java/uk/gov/hmcts/reform/ccd/documentam/controller/advice/CaseDocumentControllerAdviceTest.java
src/test/java/uk/gov/hmcts/reform/ccd/documentam/controller/advice/HttpClientExceptionWrapperTest.java

https://tools.hmcts.net/jira/browse/CCD-6536
```
[ ] Yes
[ ] No
```

add file contentType to the streamed request

---

src/main/java/uk/gov/hmcts/reform/ccd/documentam/configuration/ApplicationConfiguration.java
src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/CCD-6667
```
[ ] Yes
[ ] No
```

add custom bean to setMaxPartCount to -1
